baseURL = "https://esg.dev/"
languageCode = "en-us"
title = "ESG's"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = "UA-145113644-1"
enableRobotsTXT = true
show_reading_time = false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
  
[params]
  twitter = "https://twitter.com/Eric_STG"
  github = "https://github.com/EricStG"
  linkedin = "https://www.linkedin.com/in/eric-st-georges/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
