baseURL = "https://esg.dev/"
languageCode = "en-us"
title = "ESG's"

DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
googleAnalytics = "UA-145113644-1"
enableRobotsTXT = true
show_reading_time = false

theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
  
[params]
  twitter = "https://twitter.com/Eric_STG"
  github = "https://github.com/EricStG"
  linkedin = "https://www.linkedin.com/in/eric-st-georges/"
  stackoverflow = "https://stackoverflow.com/users/1251127/esg"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = 1
	
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    pre = "<i class='fa fa-heart'></i>"
    url = "/posts/"
    weight = 10
	
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    pre = "<i class='fa fa-heart'></i>"
    url = "/tags/"
    weight = 20

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "keywords"
    weight = 100
