baseURL = "https://esg.dev/"
languageCode = "en-us"
title = "ESG's"

DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
enableRobotsTXT = false
show_reading_time = false

[module]
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = false
    path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[services]
  [services.googleAnalytics]
    id = "G-FTQQ7H86XR"

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
  
[params]
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[params.ananke.social.follow]
  new_window_icon = true
  networks = [
    "mastodon",
    "bluesky",
    "github",
    "linkedin",
    "stackoverflow"
  ]

[params.ananke.social.bluesky]
  username = "esg.dev"

[params.ananke.social.github]
  username = "EricStG"

[params.ananke.social.linkedin]
  username = "eric-st-georges"

[params.ananke.social.mastodon]
  profilelink = "https://hachyderm.io/@esg"
  rel = "me"

[params.ananke.social.stackoverflow]
  username = "1251127"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = 1
	
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    pre = "<i class='fa fa-heart'></i>"
    url = "/posts/"
    weight = 10
	
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    pre = "<i class='fa fa-heart'></i>"
    url = "/tags/"
    weight = 20

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "keywords"
    weight = 100
