# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      HUGO_ENV: production    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Publish Site
      uses: chabad360/hugo-gh-pages@master
      with:
        githubToken: ${{ secrets.PERSONAL_TOKEN }}
        cname: esg.dev # Or anything else
        branch: master # Or anything else
        args: --gc --minify --cleanDestinationDir
