name: gh-pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_ENV: production
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Publish Site
      uses: chabad360/hugo-gh-pages@master
      with:
        githubToken: ${{ secrets.PERSONAL_TOKEN }}
        cname: esg.dev
        siteDir: /github/workspace/src/hugo
        args: --gc --minify --cleanDestinationDir
